### ISSUE TITLE
Stopwatch is not started

### ISSUE THREAD

**Issue by samuelabj** [visualeyes/budgerigar#1]
```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Stopwatch is not started
   at Budgerigar.Timing.StopWatch.StopwatchPerformanceMonitorStep..ctor(String name, Stopwatch stopwatch)
   at Budgerigar.Timing.StopWatch.StopwatchPerformanceTimerMonitor.Step(String name)
   at Budgerigar.Budgetting.PerformanceBudget.CreateStep(String name)
   at Budgerigar.Budgetting.PerformanceBudgetExtensions.Step(PerformanceBudget budget, String name)
```

**Comment by johncmckim** [comment]
This was caused by not awaiting a task.

```
    public Task<int> PrepareAsync(IEmailBuilder email, int? fromAdminId) {
        using (var budget = budgetter.RunWithBudget("test", 100M, null)) {
            ....
            return thing.DoThingAsync(budget);
        }
    }
```

The budget gets disposed before the task completes and the task still tries to create steps after it is disposed.
